site_name: MDL
theme: slate
docs_dir: src
site_dir: public
repo_url: https://github.com/MethodsDev/mdl-site
edit_uri: edit/main/src/
extra_css:
    - css/extra.css
nav:
    - 'index.md'
    - 'vision.md'
    - Team: 'team.md'
    - Docs: 'comp-docs/index.md'
plugins:
  - search
markdown_extensions:
  - attr_list
  - tables
